import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    background: 'rgba(251, 252, 253, 1)',
    divider: 'rgb(34, 150, 243)',
    light: 'rgb(16, 38, 73)',
    surface: 'rgb(56, 56, 56)',
    error: 'rgb(18, 20, 44)',
    lightInverse: 'rgb(86, 200, 90)',
    medium: 'rgb(237, 237, 237)',
    strongInverse: 'rgb(238, 238, 238)',
    mediumInverse: 'rgb(245, 145, 32)',
    primary: 'rgb(246, 69, 84)',
    custom_rgba246_69_84_056: 'rgba(246, 69, 84, 0.56)',
    secondary: 'rgb(255, 255, 255)',
    strong: 'rgba(255, 255, 255, 0.94)',
    custom_rgba0_0_0_1: 'rgba(0, 0, 0, 1)',
  },
  typography: {
    body1: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      fontFamily: 'OpenSansRegular',
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      fontFamily: 'OpenSansSemiBold',
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      fontFamily: 'OpenSansRegular',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom14: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom15: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom16: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom17: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom18: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom19: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom20: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom21: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom22: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom23: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom24: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom25: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom26: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom27: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom28: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom29: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom30: {
      ...systemWeights.regular,
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom31: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom32: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom33: {
      fontFamily: 'OpenSansRegularItalic',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom34: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom35: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom36: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom37: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom38: {
      fontFamily: 'OpenSansRegular',
      fontSize: 8,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom39: {
      fontFamily: 'OpenSansBold',
      fontSize: 30,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom40: {
      fontFamily: 'OpenSansBold',
      fontSize: 30,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom41: {
      fontFamily: 'OpenSansBold',
      fontSize: 40,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom42: {
      fontFamily: 'OpenSansBold',
      fontSize: 40,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom43: {
      fontFamily: 'OpenSansBold',
      fontSize: 40,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom44: {
      fontFamily: 'OpenSansBold',
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom45: {
      fontFamily: 'OpenSansBold',
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    custom46: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    custom47: {
      fontFamily: 'OpenSansRegular',
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    custom48: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom49: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom50: {
      fontFamily: 'OpenSansSemiBold',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom51: {
      fontFamily: 'OpenSansBold',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom52: {
      fontFamily: 'OpenSansBold',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom53: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom54: {
      fontFamily: 'OpenSansRegular',
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    headline1: {
      fontFamily: 'OpenSansBold',
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      fontFamily: 'OpenSansBold',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      fontFamily: 'OpenSansLight',
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      fontFamily: 'OpenSansLight',
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
  },
};
